version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ome_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_matching_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local


